// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoPonto.Migrations
{
    [DbContext(typeof(TransporteDbContext))]
    [Migration("20260926011413_RuntimeEstruturalEtapa3")]
    partial class RuntimeEstruturalEtapa3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoPonto.Domain.Entities.EventoViagemPersistido", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("TimestampEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("TimestampEvento");

                    b.ToTable("EventosViagem");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.FonteEstrutural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FontesEstruturais", (string)null);
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.HistoricoPassagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoLinha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanciaParadaMetros")
                        .HasColumnType("double precision");

                    b.Property<double?>("DistanciaTrechoMetros")
                        .HasColumnType("double precision");

                    b.Property<int>("HoraDia")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OcorrenciaParadaPadraoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ordem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PadraoVersaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParadaItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<double>("PosicaoNaRota")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TempoDesdeParadaAnteriorSegundos")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("TimestampGps")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimestampPassagem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimestampRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VelocidadeInstantanea")
                        .HasColumnType("double precision");

                    b.Property<double?>("VelocidadeMedia")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ViagemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Volta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaParadaPadraoId");

                    b.HasIndex("PadraoVersaoId");

                    b.HasIndex("TimestampGps");

                    b.HasIndex("CodigoLinha", "TimestampPassagem");

                    b.HasIndex("ItinerarioId", "TimestampPassagem");

                    b.HasIndex("Ordem", "TimestampGps");

                    b.HasIndex("Ordem", "TimestampPassagem");

                    b.HasIndex("ParadaId", "TimestampGps");

                    b.HasIndex("ParadaItinerarioId", "TimestampPassagem");

                    b.HasIndex("SentidoId", "TimestampPassagem");

                    b.HasIndex("ViagemId", "ParadaItinerarioId")
                        .IsUnique()
                        .HasFilter("\"ViagemId\" IS NOT NULL AND \"ParadaItinerarioId\" IS NOT NULL");

                    b.HasIndex("ViagemId", "TimestampPassagem");

                    b.HasIndex("CodigoLinha", "ItinerarioId", "TimestampGps");

                    b.HasIndex("ViagemId", "OcorrenciaParadaPadraoId", "Volta")
                        .IsUnique()
                        .HasFilter("\"ViagemId\" IS NOT NULL AND \"OcorrenciaParadaPadraoId\" IS NOT NULL AND \"Volta\" IS NOT NULL");

                    b.ToTable("HistoricoPassagens");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ImportacaoEstrutural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgoritmoVersao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("ConcluidaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConteudoHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("FonteEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IniciadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Relatorio")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("VersaoFonte")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("FonteEstruturalId", "IniciadaEmUtc");

                    b.HasIndex("FonteEstruturalId", "ConteudoHash", "AlgoritmoVersao")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'CONCLUIDA'");

                    b.ToTable("ImportacoesEstruturais", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportacoesEstruturais_Status", "\"Status\" IN ('EM_PROCESSAMENTO','CONCLUIDA','FALHOU')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Itinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<LineString>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<Guid>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Geometria");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometria"), "GIST");

                    b.HasIndex("SentidoId");

                    b.ToTable("Itinerarios");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Consorcio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModalId");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.LinhaIdentidadeExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double?>("Confianca")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("FonteEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrigemMapeamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.HasIndex("FonteEstruturalId", "Tipo", "ExternalId")
                        .IsUnique();

                    b.ToTable("LinhasIdentidadesExternas", null, t =>
                        {
                            t.HasCheckConstraint("CK_LinhasIdentidadesExternas_Confianca", "\"Confianca\" IS NULL OR (\"Confianca\" >= 0 AND \"Confianca\" <= 1)");

                            t.HasCheckConstraint("CK_LinhasIdentidadesExternas_OrigemMapeamento", "\"OrigemMapeamento\" IN ('FONTE','MANUAL')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Modal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Modais");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.OcorrenciaParadaPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DistanciaAcumuladaMetros")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanciaDaLinhaMetros")
                        .HasColumnType("double precision");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("PadraoVersaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<double>("PosicaoTracado")
                        .HasColumnType("double precision");

                    b.Property<int?>("SourceSequence")
                        .HasColumnType("integer");

                    b.Property<double?>("SourceShapeDistTraveledMetros")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ParadaId");

                    b.HasIndex("PadraoVersaoId", "Ordem")
                        .IsUnique();

                    b.HasIndex("PadraoVersaoId", "PosicaoTracado");

                    b.ToTable("OcorrenciasParadasPadroes", null, t =>
                        {
                            t.HasCheckConstraint("CK_OcorrenciasPadroes_Distancias", "\"DistanciaAcumuladaMetros\" >= 0 AND \"DistanciaDaLinhaMetros\" >= 0");

                            t.HasCheckConstraint("CK_OcorrenciasPadroes_Ordem", "\"Ordem\" > 0");

                            t.HasCheckConstraint("CK_OcorrenciasPadroes_Posicao", "\"PosicaoTracado\" >= 0 AND \"PosicaoTracado\" <= 1");

                            t.HasCheckConstraint("CK_OcorrenciasPadroes_SourceSequence", "\"SourceSequence\" IS NULL OR \"SourceSequence\" >= 0");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.OverrideOcorrenciaPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ObsoletoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrdemDesejada")
                        .HasColumnType("integer");

                    b.Property<Guid>("PadraoOperacionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevalidadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParadaId");

                    b.HasIndex("PadraoOperacionalId", "Ativo");

                    b.ToTable("OverridesOcorrenciasPadroes", null, t =>
                        {
                            t.HasCheckConstraint("CK_OverridesOcorrencias_AcaoOrdem", "(\"Acao\" = 'EXCLUIR' AND \"OrdemDesejada\" IS NULL) OR (\"Acao\" IN ('INCLUIR','MOVER') AND \"OrdemDesejada\" > 0)");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoIdentidadeExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double?>("Confianca")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("FonteEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrigemMapeamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PadraoOperacionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PadraoOperacionalId");

                    b.HasIndex("FonteEstruturalId", "Tipo", "ExternalId")
                        .IsUnique();

                    b.ToTable("PadroesIdentidadesExternas", null, t =>
                        {
                            t.HasCheckConstraint("CK_PadroesIdentidadesExternas_Confianca", "\"Confianca\" IS NULL OR (\"Confianca\" >= 0 AND \"Confianca\" <= 1)");

                            t.HasCheckConstraint("CK_PadroesIdentidadesExternas_OrigemMapeamento", "\"OrigemMapeamento\" IN ('FONTE','MANUAL')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoOperacional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomePublico")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VersaoAtualId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id", "VersaoAtualId");

                    b.HasIndex("SentidoId", "Chave")
                        .IsUnique();

                    b.ToTable("PadroesOperacionais", (string)null);
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgoritmoVersao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("ComprimentoMetros")
                        .HasColumnType("double precision");

                    b.Property<double>("Confianca")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LineString>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<string>("HashEstrutural")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetodoConstrucao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("PadraoOperacionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublicadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Relatorio")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultadoValidacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Topologia")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Geometria");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometria"), "GIST");

                    b.HasIndex("PadraoOperacionalId", "HashEstrutural")
                        .IsUnique();

                    b.HasIndex("PadraoOperacionalId", "Numero")
                        .IsUnique();

                    b.ToTable("PadroesVersoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_PadroesVersoes_Comprimento", "\"ComprimentoMetros\" >= 0");

                            t.HasCheckConstraint("CK_PadroesVersoes_Confianca", "\"Confianca\" >= 0 AND \"Confianca\" <= 1");

                            t.HasCheckConstraint("CK_PadroesVersoes_Numero", "\"Numero\" > 0");

                            t.HasCheckConstraint("CK_PadroesVersoes_Topologia", "\"Topologia\" IN ('LINEAR','CIRCULAR')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoVersaoImportacao", b =>
                {
                    b.Property<Guid>("PadraoVersaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportacaoEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Papel")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("PadraoVersaoId", "ImportacaoEstruturalId", "Papel");

                    b.HasIndex("ImportacaoEstruturalId");

                    b.ToTable("PadroesVersoesImportacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_PadroesVersoesImportacoes_Papel", "\"Papel\" IN ('MEMBERSHIP','GEOMETRIA','PARADAS','METADADOS')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveCanonica")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<Guid?>("ModalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParadaPaiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plataforma")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipoLocal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChaveCanonica")
                        .IsUnique()
                        .HasFilter("\"ChaveCanonica\" IS NOT NULL");

                    b.HasIndex("Localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "GIST");

                    b.HasIndex("ModalId");

                    b.HasIndex("ParadaPaiId");

                    b.ToTable("Paradas", t =>
                        {
                            t.HasCheckConstraint("CK_Paradas_TipoLocal", "\"TipoLocal\" IN ('PARADA','PLATAFORMA','ESTACAO')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaIdentidadeExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double?>("Confianca")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("FonteEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrigemMapeamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParadaId");

                    b.HasIndex("FonteEstruturalId", "Tipo", "ExternalId")
                        .IsUnique();

                    b.ToTable("ParadasIdentidadesExternas", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParadasIdentidadesExternas_Confianca", "\"Confianca\" IS NULL OR (\"Confianca\" >= 0 AND \"Confianca\" <= 1)");

                            t.HasCheckConstraint("CK_ParadasIdentidadesExternas_OrigemMapeamento", "\"OrigemMapeamento\" IN ('FONTE','MANUAL')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaItinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("SPATIAL_LEGACY");

                    b.Property<Guid?>("ImportacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<double>("PosicaoLinha")
                        .HasColumnType("double precision");

                    b.Property<double?>("SourceShapeDistTraveledMetros")
                        .HasColumnType("double precision");

                    b.Property<int?>("SourceStopSequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubstituidaPorImportacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.HasIndex("ItinerarioId");

                    b.HasIndex("ParadaId");

                    b.HasIndex("SubstituidaPorImportacaoId");

                    b.HasIndex("ItinerarioId", "Ordem")
                        .IsUnique()
                        .HasFilter("\"Ativo\" = true");

                    b.ToTable("ParadasItinerario");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Poi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "GIST");

                    b.ToTable("Pois");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PoiParada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParadaId");

                    b.HasIndex("PoiId");

                    b.HasIndex("ParadaId", "PoiId")
                        .IsUnique();

                    b.ToTable("PoiParadas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PosicaoVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Direcao")
                        .HasColumnType("double precision");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.Property<double>("Velocidade")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("PosicoesVeiculo");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PositionCorrectionShadowOrigin", b =>
                {
                    b.Property<string>("ShadowOriginId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AmostrasCausais")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CandidateResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CausalStateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoLinha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double>("ComprimentoRotaMetros")
                        .HasColumnType("double precision");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EstadoMovimento")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSamplesConfigured")
                        .HasColumnType("integer");

                    b.Property<bool>("MaxSamplesReached")
                        .HasColumnType("boolean");

                    b.Property<string>("Modal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ObservacaoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OcorrenciaParadaPadraoId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrdemVeiculo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("PadraoVersaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PersistidoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("PosicaoB")
                        .HasColumnType("double precision");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("RecebidoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SamplesBeforeCap")
                        .HasColumnType("integer");

                    b.Property<int>("SamplesUsed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<string>("SinaisParada")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("TimestampGpsOrigemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("VelocidadeInstantaneaKmh")
                        .HasColumnType("double precision");

                    b.Property<double?>("VelocidadeMediaLegacyKmh")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ViagemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Volta")
                        .HasColumnType("integer");

                    b.HasKey("ShadowOriginId");

                    b.HasIndex("ObservacaoId");

                    b.HasIndex("OcorrenciaParadaPadraoId");

                    b.HasIndex("PadraoVersaoId");

                    b.HasIndex("TimestampGpsOrigemUtc");

                    b.HasIndex("PolicyFingerprint", "TimestampGpsOrigemUtc");

                    b.ToTable("PositionCorrectionShadowOrigins", (string)null);
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Sentidos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.SentidoIdentidadeExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double?>("Confianca")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("FonteEstruturalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrigemMapeamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SentidoId");

                    b.HasIndex("FonteEstruturalId", "Tipo", "ExternalId")
                        .IsUnique();

                    b.ToTable("SentidosIdentidadesExternas", null, t =>
                        {
                            t.HasCheckConstraint("CK_SentidosIdentidadesExternas_Confianca", "\"Confianca\" IS NULL OR (\"Confianca\" >= 0 AND \"Confianca\" <= 1)");

                            t.HasCheckConstraint("CK_SentidosIdentidadesExternas_OrigemMapeamento", "\"OrigemMapeamento\" IN ('FONTE','MANUAL')");
                        });
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Tarifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidoDe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("Tarifa");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.HasIndex("ModalId");

                    b.HasIndex("LinhaId", "ValidoDe");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.TelemetriaVeiculoMl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double?>("Bearing")
                        .HasColumnType("double precision");

                    b.Property<string>("CodigoLinha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double?>("ComprimentoRotaMetros")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanciaProximaParadaMetros")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EventoCriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<double?>("LatitudeProjetada")
                        .HasColumnType("double precision");

                    b.Property<double>("LatitudeRecebida")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<double?>("LongitudeProjetada")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudeRecebida")
                        .HasColumnType("double precision");

                    b.Property<string>("Modal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ObservacaoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OcorrenciaParadaPadraoId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrdemVeiculo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("OrigemPosicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PadraoVersaoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PosicaoNaRota")
                        .HasColumnType("double precision");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ProximaParadaItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecebidoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TimestampEnvioFonte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimestampGps")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimestampServidorFonte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VelocidadeInstantanea")
                        .HasColumnType("double precision");

                    b.Property<double?>("VelocidadeMediaCausal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ViagemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Volta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObservacaoId")
                        .IsUnique();

                    b.HasIndex("OcorrenciaParadaPadraoId");

                    b.HasIndex("PadraoVersaoId");

                    b.HasIndex("CodigoLinha", "TimestampGps");

                    b.HasIndex("OrdemVeiculo", "TimestampGps");

                    b.HasIndex("ViagemId", "TimestampGps")
                        .HasFilter("\"ViagemId\" IS NOT NULL");

                    b.ToTable("TelemetriasVeiculoMl");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.HistoricoPassagem", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Itinerario", "Itinerario")
                        .WithMany()
                        .HasForeignKey("ItinerarioId");

                    b.HasOne("NoPonto.Domain.Entities.OcorrenciaParadaPadrao", null)
                        .WithMany()
                        .HasForeignKey("OcorrenciaParadaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", null)
                        .WithMany()
                        .HasForeignKey("PadraoVersaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.ParadaItinerario", "ParadaItinerario")
                        .WithMany()
                        .HasForeignKey("ParadaItinerarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.Sentido", "Sentido")
                        .WithMany()
                        .HasForeignKey("SentidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Itinerario");

                    b.Navigation("Parada");

                    b.Navigation("ParadaItinerario");

                    b.Navigation("Sentido");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ImportacaoEstrutural", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.FonteEstrutural", "FonteEstrutural")
                        .WithMany("Importacoes")
                        .HasForeignKey("FonteEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FonteEstrutural");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Itinerario", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Sentido", "Sentido")
                        .WithMany("Itinerarios")
                        .HasForeignKey("SentidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentido");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Modal", "Modal")
                        .WithMany("Linhas")
                        .HasForeignKey("ModalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modal");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.LinhaIdentidadeExterna", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.FonteEstrutural", "FonteEstrutural")
                        .WithMany()
                        .HasForeignKey("FonteEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteEstrutural");

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.OcorrenciaParadaPadrao", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", "PadraoVersao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("PadraoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PadraoVersao");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.OverrideOcorrenciaPadrao", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.PadraoOperacional", "PadraoOperacional")
                        .WithMany()
                        .HasForeignKey("PadraoOperacionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PadraoOperacional");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoIdentidadeExterna", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.FonteEstrutural", "FonteEstrutural")
                        .WithMany()
                        .HasForeignKey("FonteEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.PadraoOperacional", "PadraoOperacional")
                        .WithMany("IdentidadesExternas")
                        .HasForeignKey("PadraoOperacionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteEstrutural");

                    b.Navigation("PadraoOperacional");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoOperacional", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Sentido", "Sentido")
                        .WithMany()
                        .HasForeignKey("SentidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", "VersaoAtual")
                        .WithMany()
                        .HasForeignKey("Id", "VersaoAtualId")
                        .HasPrincipalKey("PadraoOperacionalId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sentido");

                    b.Navigation("VersaoAtual");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoVersao", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.PadraoOperacional", "PadraoOperacional")
                        .WithMany("Versoes")
                        .HasForeignKey("PadraoOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PadraoOperacional");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoVersaoImportacao", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.ImportacaoEstrutural", "ImportacaoEstrutural")
                        .WithMany("PadroesVersoes")
                        .HasForeignKey("ImportacaoEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", "PadraoVersao")
                        .WithMany("Importacoes")
                        .HasForeignKey("PadraoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportacaoEstrutural");

                    b.Navigation("PadraoVersao");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Parada", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Modal", "Modal")
                        .WithMany()
                        .HasForeignKey("ModalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.Parada", "ParadaPai")
                        .WithMany()
                        .HasForeignKey("ParadaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modal");

                    b.Navigation("ParadaPai");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaIdentidadeExterna", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.FonteEstrutural", "FonteEstrutural")
                        .WithMany()
                        .HasForeignKey("FonteEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteEstrutural");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaItinerario", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Itinerario", "Itinerario")
                        .WithMany()
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany("ParadasItinerario")
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PoiParada", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Poi", "Poi")
                        .WithMany("PoiParadas")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parada");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PosicaoVeiculo", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Posicoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PositionCorrectionShadowOrigin", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.OcorrenciaParadaPadrao", null)
                        .WithMany()
                        .HasForeignKey("OcorrenciaParadaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", null)
                        .WithMany()
                        .HasForeignKey("PadraoVersaoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany("Sentidos")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.SentidoIdentidadeExterna", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.FonteEstrutural", "FonteEstrutural")
                        .WithMany()
                        .HasForeignKey("FonteEstruturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Sentido", "Sentido")
                        .WithMany()
                        .HasForeignKey("SentidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteEstrutural");

                    b.Navigation("Sentido");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Tarifa", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany("Tarifas")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Modal", "Modal")
                        .WithMany("Tarifas")
                        .HasForeignKey("ModalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");

                    b.Navigation("Modal");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.TelemetriaVeiculoMl", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.OcorrenciaParadaPadrao", null)
                        .WithMany()
                        .HasForeignKey("OcorrenciaParadaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoPonto.Domain.Entities.PadraoVersao", null)
                        .WithMany()
                        .HasForeignKey("PadraoVersaoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany("Veiculos")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.FonteEstrutural", b =>
                {
                    b.Navigation("Importacoes");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ImportacaoEstrutural", b =>
                {
                    b.Navigation("PadroesVersoes");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.Navigation("Sentidos");

                    b.Navigation("Tarifas");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Modal", b =>
                {
                    b.Navigation("Linhas");

                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoOperacional", b =>
                {
                    b.Navigation("IdentidadesExternas");

                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PadraoVersao", b =>
                {
                    b.Navigation("Importacoes");

                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Parada", b =>
                {
                    b.Navigation("ParadasItinerario");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Poi", b =>
                {
                    b.Navigation("PoiParadas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.Navigation("Itinerarios");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Posicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
