// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoPonto.Migrations
{
    [DbContext(typeof(TransporteDbContext))]
    partial class TransporteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoPonto.Domain.Entities.Itinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<LineString>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<Guid>("SentidoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SentidoId");

                    b.ToTable("Itinerarios");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModalId");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Modal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Modais");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "GIST");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaItinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItinerarioId");

                    b.HasIndex("ParadaId");

                    b.ToTable("ParadasItinerario");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Poi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "GIST");

                    b.ToTable("Pois");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PoiItinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItinerarioId");

                    b.HasIndex("PoiId");

                    b.ToTable("PoisItinerario");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PosicaoVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Direcao")
                        .HasColumnType("double precision");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.Property<double>("Velocidade")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("PosicoesVeiculo");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Sentidos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Itinerario", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Sentido", "Sentido")
                        .WithMany("Itinerarios")
                        .HasForeignKey("SentidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentido");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Modal", "Modal")
                        .WithMany("Linhas")
                        .HasForeignKey("ModalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modal");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.ParadaItinerario", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Itinerario", "Itinerario")
                        .WithMany()
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Parada", "Parada")
                        .WithMany("ParadasItinerario")
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PoiItinerario", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Itinerario", "Itinerario")
                        .WithMany()
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoPonto.Domain.Entities.Poi", "Poi")
                        .WithMany("PoiItinerarios")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.PosicaoVeiculo", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Posicoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany("Sentidos")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("NoPonto.Domain.Entities.Linha", "Linha")
                        .WithMany("Veiculos")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Linha", b =>
                {
                    b.Navigation("Sentidos");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Modal", b =>
                {
                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Parada", b =>
                {
                    b.Navigation("ParadasItinerario");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Poi", b =>
                {
                    b.Navigation("PoiItinerarios");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Sentido", b =>
                {
                    b.Navigation("Itinerarios");
                });

            modelBuilder.Entity("NoPonto.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Posicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
